version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    command: ["nginx", "-g", "daemon off;"]

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://user:password@database/predictions_db  # Pass database URL

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: predictions_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
